--- 
- name: spring pet clinic 
  hosts: all 
  become: true 
  tasks: 
    - name: copy the spc jar file 
      ansible.builtin.copy: 
        src: /home/jenkins/root/workspace/spc_release/target/spring-petclinic-3.0.0-SNAPSHOT.jar 
        remote_src: true
        dest: /tmp/ 
    - name: copy the unit service file
      ansible.builtin.copy: 
        src: spc.service 
        dest: /etc/systemd/system/spc.service 
    - name: file permissions 
      ansible.builtin.file: 
        path: /etc/systemd/system/spc.service 
        mode: '664'
        state: file 
    - name: service file 
      ansible.builtin.systemd: 
        daemon_reload: true 
        enabled: true 
        name: spc.service 
        state: started